### PR TITLE
Make pjson keep the order of keys by default

### PR DESCRIPTION
**Pull request by Jamim**

### CODE REVIEW

**Review by carstene1ns — APPROVED** [review]

**Comment by igorgue** [comment]
@Jamim & @carstene1ns thanks for the collaboration 👍 I've updated the package to the new version!

I'm trying to upgrade the package... But I'm getting on the web `1.0` instead of `1.1`

https://pypi.org/project/pjson/

And my package doesn't look like it uploaded, this is what I get when I run:

`python3 setup.py sdist upload -r https://pypi.org/project/pjson`

```running sdist
running egg_info
writing pjson.egg-info/PKG-INFO
writing dependency_links to pjson.egg-info/dependency_links.txt
writing entry points to pjson.egg-info/entry_points.txt
writing requirements to pjson.egg-info/requires.txt
writing top-level names to pjson.egg-info/top_level.txt
reading manifest file 'pjson.egg-info/SOURCES.txt'
writing manifest file 'pjson.egg-info/SOURCES.txt'
warning: sdist: standard file not found: should have one of README, README.rst, README.txt

running check
creating pjson-1.1
creating pjson-1.1/pjson
creating pjson-1.1/pjson.egg-info
copying files to pjson-1.1...
copying setup.py -> pjson-1.1
copying pjson/__init__.py -> pjson-1.1/pjson
copying pjson/__main__.py -> pjson-1.1/pjson
copying pjson/core.py -> pjson-1.1/pjson
copying pjson.egg-info/PKG-INFO -> pjson-1.1/pjson.egg-info
copying pjson.egg-info/SOURCES.txt -> pjson-1.1/pjson.egg-info
copying pjson.egg-info/dependency_links.txt -> pjson-1.1/pjson.egg-info
copying pjson.egg-info/entry_points.txt -> pjson-1.1/pjson.egg-info
copying pjson.egg-info/requires.txt -> pjson-1.1/pjson.egg-info
copying pjson.egg-info/top_level.txt -> pjson-1.1/pjson.egg-info
Writing pjson-1.1/setup.cfg
Creating tar archive
removing 'pjson-1.1' (and everything under it)
running upload
Password: 
Submitting dist/pjson-1.1.tar.gz to https://pypi.org/project/pjson
Server response (200): OK
```

Do you guys happen to know what is this problem?

**Comment by carstene1ns** [comment]
It seems the repository URL you use is outdated (`-r`). You may simply use the default url of the tool.
Documentation I found about the new pypi API does not use it anymore, but a configuration file instead:
https://packaging.python.org/guides/migrating-to-pypi-org/ (using `~/.pypirc`)

`distutils` seems preferred over `setuptools` nowadays, Mini-Howto:
Change first line of `setup.py` to
```python
from distutils.core import setup
```

Also people tend to use `twine` nowadays for uploading, because it is more secure:
https://pypi.python.org/pypi/twine#usage

Btw. about the missing `README.txt` file warning, you could create a `setup.cfg` file with the following content:
```ini
[metadata]
description-file = README.md
```

Hope this helps.

**Comment by igorgue** [comment]
@carstene1ns Thank you so much, and for the update, I really haven't done Python as much lately (but `pjson` is still my favorite tool), but I will soon, so I appreciate it.

I'll make the change, this weekend and push a new version.

**Comment by igorgue** [comment]
Was able to fix it, thank you!

**Pull request merged**
